// -----------------------------------------------------------------------------
// b2b_pcie_fd_driver — sided PIPE-ingress driver (Phase I I8b).
//
// One class, two instances: `is_b`=0 injects into bridge A's PIPE RX (the forward
// direction), `is_b`=1 injects into bridge B's PIPE RX (the reverse direction).
// Same recipe as the half-duplex b2b_pcie_driver -- replay the shared PRE-FRAMED,
// block-aligned PIPE word stream (+VEC_WORDS, generated by framing_model, the SAME
// words the DUT framer emits) one word per pclk after a short warmup -- but the
// PIPE RX signal set is selected by `is_b` (SV has no dynamic field access, so the
// two sides branch). inject() is forked by the test. Publishes each injected word
// on ref_ap as this direction's reference. Mirrors the PyUVM _drive.
// -----------------------------------------------------------------------------
class b2b_pcie_fd_driver extends uvm_component;
  virtual b2b_pcie_fd_if vif;
  bit                    is_b;   // 0 = inject A (forward), 1 = inject B (reverse)
  uvm_analysis_port#(bit [PW-1:0]) ref_ap;   // injected words -> scoreboard ref
  localparam int unsigned WARMUP_PCLK = 4;
  `uvm_component_utils(b2b_pcie_fd_driver)
  function new(string name, uvm_component parent);
    super.new(name, parent);
    ref_ap = new("ref_ap", this);
  endfunction

  virtual task inject();
    string         vec;
    logic [PW-1:0] mem [int];   // associative: $readmemh-compatible, unbounded
    if (!$value$plusargs("VEC_WORDS=%s", vec))
      `uvm_fatal("B2BPFD", "b2b_pcie_fd_driver requires +VEC_WORDS=<framed word .vec>");
    $readmemh(vec, mem);
    repeat (WARMUP_PCLK) @(posedge vif.pclk);
    for (int i = 0; mem.exists(i); i++) begin
      @(posedge vif.pclk); #0.1;
      if (is_b) begin vif.b_rx_data = mem[i]; vif.b_rx_valid = 1'b1; end
      else      begin vif.a_rx_data = mem[i]; vif.a_rx_valid = 1'b1; end
      ref_ap.write(mem[i]);
    end
    @(posedge vif.pclk); #0.1;
    if (is_b) begin vif.b_rx_valid = 1'b0; vif.b_rx_data = '0; end
    else      begin vif.a_rx_valid = 1'b0; vif.a_rx_data = '0; end
  endtask
endclass
