// -----------------------------------------------------------------------------
// b2b_pcie_driver — PIPE-ingress driver for bridge A (PLAN H2).
//
// The SV UVM tier has no framer, so it replays a PRE-FRAMED, block-aligned PIPE
// word stream generated by the shared model (dv/common/vectors gen_vectors.py
// --words-out, framing_model.frame_stream) -- the SAME words the DUT framer emits,
// so this exercises bridge A's deframer exactly as the proven PHY loopback does.
// Reads +VEC_WORDS (one PW-bit word per line, $readmemh) and drives one word per
// pclk after a short warmup (letting both internal FDI links reach ACTIVE), and
// publishes each injected word as the reference for bridge B's re-framed output.
// inject() is forked by the test. Mirrors the PyUVM _drive_rx.
// -----------------------------------------------------------------------------
class b2b_pcie_driver extends uvm_component;
  virtual b2b_pcie_if vif;
  uvm_analysis_port#(bit [PW-1:0]) ref_ap;   // injected words -> scoreboard ref
  localparam int unsigned WARMUP_PCLK = 4;
  `uvm_component_utils(b2b_pcie_driver)
  function new(string name, uvm_component parent);
    super.new(name, parent);
    ref_ap = new("ref_ap", this);
  endfunction

  virtual task inject();
    string           vec;
    logic [PW-1:0]   mem [int];   // associative: $readmemh-compatible, unbounded
    if (!$value$plusargs("VEC_WORDS=%s", vec))
      `uvm_fatal("B2BP", "b2b_pcie_driver requires +VEC_WORDS=<framed word .vec>");
    $readmemh(vec, mem);
    repeat (WARMUP_PCLK) @(posedge vif.pclk);
    for (int i = 0; mem.exists(i); i++) begin
      @(posedge vif.pclk); #0.1;
      vif.a_rx_data  = mem[i];
      vif.a_rx_valid = 1'b1;
      ref_ap.write(mem[i]);
    end
    @(posedge vif.pclk); #0.1;
    vif.a_rx_valid = 1'b0;
    vif.a_rx_data  = '0;
  endtask
endclass
